
#Configuration file for Pytest. 

#Centralizes all your fixtures, variables and default execution flags
#Default command-line flags
#Home of custom pytest markers

#examples: playwright can take screenshots on test failures or run test in parallel

[pytest]
markers = ui: marks tests as UI tests

